/** Generated by tools/build_assets.py — do not edit by hand. */
export const SPRITE_META = {
  "cliffs/clouds": {
    "src": "assets/gv/cliffs/clouds.png"
  },
  "cliffs/far-grounds": {
    "src": "assets/gv/cliffs/far-grounds.png"
  },
  "cliffs/sea": {
    "src": "assets/gv/cliffs/sea.png"
  },
  "cliffs/sky": {
    "src": "assets/gv/cliffs/sky.png"
  },
  "cliffs/tileset": {
    "src": "assets/gv/cliffs/tileset.png"
  },
  "enemy/ghost": {
    "fh": 50,
    "fps": 8,
    "frames": 4,
    "fw": 38,
    "src": "assets/gv/enemy/ghost.png"
  },
  "enemy/skeleton": {
    "fh": 46,
    "fps": 10,
    "frames": 8,
    "fw": 50,
    "src": "assets/gv/enemy/skeleton.png"
  },
  "enemy/skeleton_clothed": {
    "fh": 46,
    "fps": 9,
    "frames": 8,
    "fw": 50,
    "src": "assets/gv/enemy/skeleton_clothed.png"
  },
  "enemy/skeleton_rise": {
    "fh": 44,
    "fps": 10,
    "frames": 6,
    "fw": 50,
    "src": "assets/gv/enemy/skeleton_rise.png"
  },
  "enemy/wolf": {
    "fh": 22,
    "fps": 12,
    "frames": 4,
    "fw": 48,
    "src": "assets/gv/enemy/wolf.png"
  },
  "fx/death": {
    "fh": 50,
    "fps": 14,
    "frames": 5,
    "fw": 28,
    "src": "assets/gv/fx/death.png"
  },
  "hero/attack": {
    "fh": 40,
    "fps": 18,
    "frames": 6,
    "fw": 104,
    "src": "assets/gv/hero/attack.png"
  },
  "hero/crouch": {
    "fh": 40,
    "fps": 10,
    "frames": 3,
    "fw": 40,
    "src": "assets/gv/hero/crouch.png"
  },
  "hero/crouch_slash": {
    "fh": 30,
    "fps": 16,
    "frames": 4,
    "fw": 108,
    "src": "assets/gv/hero/crouch_slash.png"
  },
  "hero/hurt": {
    "fh": 40,
    "fps": 10,
    "frames": 3,
    "fw": 38,
    "src": "assets/gv/hero/hurt.png"
  },
  "hero/idle": {
    "fh": 42,
    "fps": 6,
    "frames": 4,
    "fw": 38,
    "src": "assets/gv/hero/idle.png"
  },
  "hero/jump": {
    "fh": 57,
    "fps": 8,
    "frames": 5,
    "fw": 80,
    "src": "assets/gv/hero/jump.png"
  },
  "hero/jump_attack": {
    "fh": 47,
    "fps": 18,
    "frames": 6,
    "fw": 80,
    "src": "assets/gv/hero/jump_attack.png"
  },
  "hero/portrait": {
    "src": "assets/gv/hero/portrait.png"
  },
  "hero/run": {
    "fh": 44,
    "fps": 16,
    "frames": 12,
    "fw": 82,
    "src": "assets/gv/hero/run.png"
  }
};
